#!/usr/bin/env python
"""
Generated by Claude on 8/19/26.

Inspect and plot histograms stored in a histograms_2023_signal-all.pkl file
(as produced by python/make_histos.py).

Usage:
    python view_histograms.py /path/to/histograms_2023_signal-all.pkl
    python view_histograms.py /path/to/histograms_2023_signal-all.pkl --key data
    python view_histograms.py /path/to/histograms_2023_signal-all.pkl --key data --category pass
    python view_histograms.py /path/to/histograms_2023_signal-all.pkl --no-plot
"""

import argparse
import pickle
import sys
from pathlib import Path

import numpy as np


def describe(d):
    """Print a summary of every histogram in the pickle."""
    if not isinstance(d, dict):
        print(f"Top-level object is not a dict, it's a {type(d)}. Contents:")
        print(d)
        return

    print(f"Found {len(d)} key(s): {list(d.keys())}\n")
    for key, hobj in d.items():
        print(f"--- {key} ---")
        try:
            axes_info = [(ax.name, type(ax).__name__, len(ax)) for ax in hobj.axes]
            for name, kind, nbins in axes_info:
                print(f"    axis: {name:12s} ({kind}, {nbins} bins)")
            print(f"    total entries (sum): {hobj.sum()}")
            print(f"    sum incl. flow bins: {hobj.sum(flow=True)}")
            storage = type(hobj.storage_type()).__name__
            has_var = hobj.variances() is not None
            print(f"    storage: {storage}"
                  f" ({'variances available' if has_var else 'NO variances -- errors unavailable'})")
        except AttributeError:
            print(f"    (not a hist.Hist object, type={type(hobj)})")
        print()


def safe_errors(h1d):
    """
    Return per-bin uncertainties, or None if the histogram can't provide them.

    Histograms booked with Double() storage keep only bin contents, so
    .variances() returns None. Weight() storage keeps sumw2 and gives real errors.
    """
    try:
        var = h1d.variances()
    except Exception:
        return None
    if var is None:
        return None
    return np.sqrt(var)


def project_and_print(hobj, axis_name, fix=None):
    """Project onto a single axis (summing over everything else) and print bin contents."""
    index = dict(fix or {})
    # sum over every axis except the one we're projecting onto
    for ax in hobj.axes:
        if ax.name != axis_name and ax.name not in index:
            index[ax.name] = sum
    h1d = hobj[index]

    edges = None
    try:
        edges = h1d.axes[axis_name].edges
    except Exception:
        pass

    values = h1d.values()
    errors = safe_errors(h1d)

    print(f"\nProjection onto '{axis_name}' (fixed: {fix}):")
    if errors is None:
        print("  (no variances stored -- histogram uses Double() storage, "
              "so no uncertainties are available)")
        for i, v in enumerate(values):
            label = f"[{edges[i]:.1f}, {edges[i+1]:.1f})" if edges is not None else str(i)
            print(f"  bin {i:2d} {label:20s} {v:12.3f}")
    else:
        for i, (v, e) in enumerate(zip(values, errors)):
            label = f"[{edges[i]:.1f}, {edges[i+1]:.1f})" if edges is not None else str(i)
            print(f"  bin {i:2d} {label:20s} {v:12.3f} +/- {e:.3f}")

    print(f"  {'total':23s} {values.sum():12.3f}")

    return h1d


def plot(hobj, axis_name, fix, outpath):
    """Save a 1D plot of the histogram projection using mplhep."""
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import mplhep as hep
    except ImportError:
        print("matplotlib/mplhep not installed; skipping plot. "
              "Install with: pip install matplotlib mplhep --break-system-packages")
        return

    index = dict(fix or {})
    for ax in hobj.axes:
        if ax.name != axis_name and ax.name not in index:
            index[ax.name] = sum
    h1d = hobj[index]

    fig, ax = plt.subplots()
    # only draw error bars if the histogram actually stores variances
    hep.histplot(h1d, ax=ax, yerr=safe_errors(h1d) is not None)
    ax.set_title(f"{axis_name} ({fix})")
    fig.savefig(outpath)
    plt.close(fig)
    print(f"Saved plot to {outpath}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pklfile", type=str, help="Path to histograms_*.pkl file")
    parser.add_argument("--key", type=str, default=None,
                         help="Which top-level key (process) to inspect further. "
                              "If omitted, only prints the summary of all keys.")
    parser.add_argument("--axis", type=str, default="msd1",
                         help="Axis to project onto for printing/plotting (default: msd1)")
    parser.add_argument("--category", type=str, default=None,
                         help="Fix the 'category' axis, e.g. pass or fail")
    parser.add_argument("--genflavor", type=int, default=None,
                         help="Fix the 'genflavor' axis to a single integer value")
    parser.add_argument("--no-plot", action="store_true",
                         help="Skip saving a plot, just print bin contents")
    parser.add_argument("--outdir", type=str, default=".",
                         help="Directory to save plots into (default: current dir)")
    args = parser.parse_args()

    path = Path(args.pklfile)
    if not path.is_file():
        sys.exit(f"File not found: {path}")

    with open(path, "rb") as f:
        d = pickle.load(f)

    describe(d)

    if args.key is None:
        return

    if args.key not in d:
        sys.exit(f"Key '{args.key}' not found. Available keys: {list(d.keys())}")

    hobj = d[args.key]

    fix = {}
    if args.category is not None:
        fix["category"] = args.category
    if args.genflavor is not None:
        fix["genflavor"] = args.genflavor

    project_and_print(hobj, args.axis, fix=fix)

    if not args.no_plot:
        outdir = Path(args.outdir)
        outdir.mkdir(parents=True, exist_ok=True)
        outpath = outdir / f"{args.key}_{args.axis}.png"
        plot(hobj, args.axis, fix, outpath)


if __name__ == "__main__":
    main()